INSERT INTO article (picture, title)
VALUES ('adidas_longsleeve_1', 'Adidas long sleeve light green'),
        ('adidas_longsleeve_2','Adidas long sleeve multicolor'),
        ('adidas_longsleeve_3', 'Adidas long sleeve dark blue'),
        ('adidas_longsleeve_4', 'Adidas long sleeve blue with zipper'),
        ('adidas_longsleeve_5', 'Adidas long sleeve black'),
        ('adidas_longsleeve_6', 'Adidas long sleeve blue'),
        ('adidas_longsleeve_7', 'Adidas long sleeve black'),
        ('adidas_longsleeve_8', 'Adidas long sleeve orange black'),
        ('adidas_pants_1', 'Adidas pants beige'),
        ('adidas_pants_2', 'Adidas pants black'),
        ('adidas_pants_3', 'Adidas pants grey'),
        ('adidas_pants_4', 'Adidas pants light grey'),
        ('adidas_pants_5', 'Adidas pants gray with stripes'),
        ('adidas_pants_6', 'Adidas pants gray with stripes'),
        ('adidas_pants_7', 'Adidas pants black with long stripes'),
        ('adidas_pants_8', 'Adidas pants black with short stripes'),
        ('adidas_pants_9', 'Adidas pants black'),
        ('adidas_pants_10', 'Adidas pants black'),
        ('adidas_pants_11', 'Adidas pants pink'),
        ('adidas_pants_12', 'Adidas pants black with letters'),
        ('adidas_pants_13', 'Adidas pants fuchsia color'),
        ('adidas_pants_14', 'Adidas pants grey'),
        ('adidas_pants_15', 'Adidas pants white'),
        ('adidas_pants_16', 'Adidas pants gray with black stripes'),
        ('adidas_pants_17', 'Adidas pants black with color stripes'),
        ('adidas_pants_18', 'Adidas pants baggy grey'),
        ('Adidas_shorts_1', 'Adidas shorts gray with black stripes'),
        ('adidas_shorts_2', 'Adidas shorts black'),
        ('adidas_shorts_3', 'Adidas shorts red'),
        ('adidas_shorts_4', 'Adidas shorts black'),
        ('adidas_shorts_5', 'Adidas shorts yellow'),
        ('adidas_shorts_6', 'Adidas shorts blue white'),
        ('adidas_shorts_7', 'Adidas shorts black'),
        ('adidas_shorts_8', 'Adidas shorts black'),
        ('adidas_shorts_9', 'Adidas shorts black'),
        ('adidas_shorts_10', 'Adidas shorts black'),
        ('adidas_shorts_11', 'Adidas shorts black'),
        ('adidas_shorts_12', 'Adidas shorts black white'),
        ('adidas_shorts_13', 'Adidas shorts black'),
        ('adidas_shorts_14', 'Adidas shorts black'),
        ('adidas_shorts_15', 'Adidas shorts black'),
        ('adidas_shorts_16', 'Adidas shorts black'),
        ('adidas_shorts_17', 'Adidas shorts blue white'),
        ('adidas_shorts_18', 'Adidas shorts black white'),
        ('adidas_shorts_19', 'Adidas shorts total black'),
        ('adidas_shorts_20', 'Adidas shorts black'),
        ('adidas_shorts_21', 'Adidas shorts black pink'),
        ('adidas_shorts_22', 'Adidas shorts red'),
        ('adidas_t-shirt_1', 'Adidas t-shirt white'),
        ('adidas_t-shirt_2', 'Adidas t-shirt white'),
        ('adidas_t-shirt_3', 'Adidas t-shirt red'),
        ('adidas_t-shirt_4', 'Adidas t-shirt dark blue'),
        ('adidas_t-shirt_5', 'Adidas t-shirt black'),
        ('adidas_t-shirt_6', 'Adidas t-shirt red white'),
        ('adidas_t-shirt_7', 'Adidas t-shirt white'),
        ('adidas_t-shirt_8', 'Adidas t-shirt blue'),
        ('adidas_t-shirt_9', 'Adidas t-shirt white'),
        ('adidas_t-shirt_10', 'Adidas t-shirt light green'),
        ('adidas_t-shirt_11', 'Adidas t-shirt white red'),
        ('adidas_t-shirt_12', 'Adidas t-shirt black'),
        ('adidas_t-shirt_13', 'Adidas t-shirt red'),
        ('adidas_t-shirt_14', 'Adidas t-shirt red'),
        ('adidas_t-shirt_15', 'Adidas t-shirt white'),
        ('adidas_t-shirt_16', 'Adidas t-shirt green'),
        ('adidas_t-shirt_17', 'Adidas t-shirt black'),
        ('adidas_t-shirt_18', 'Adidas t-shirt light blue'),
        ('adidas_t-shirt_19', 'Adidas t-shirt grey'),
        ('adidas_t-shirt_20', 'Adidas t-shirt white multicolor'),
        ('adidas_t-shirt_21', 'Adidas t-shirt grey'),
        ('adidas_t-shirt_22', 'Adidas t-shirt pink'),
        ('adidas_t-shirt_23', 'Adidas t-shirt red'),
        ('adidas_t-shirt_24', 'Adidas t-shirt dark blue'),
        ('adidas_t-shirt_25', 'Adidas t-shirt blue'),
        ('adidas_t-shirt_26', 'Adidas t-shirt dark red'),
        ('Nike_longsleeve_1', 'Nike long sleeve '),
        ('Nike_longsleeve_2', 'Nike long sleeve '),
        ('Nike_longsleeve_3', 'Nike long sleeve '),
        ('Nike_longsleeve_4', 'Nike long sleeve '),
        ('Nike_longsleeve_5', 'Nike long sleeve '),
        ('Nike_longsleeve_6', 'Nike long sleeve '),
        ('Nike_longsleeve_7', 'Nike long sleeve '),
        ('Nike_longsleeve_8', 'Nike long sleeve '),
        ('Nike_longsleeve_9', 'Nike long sleeve '),
        ('Nike_longsleeve_10', 'Nike long sleeve '),
        ('Nike_longsleeve_11', 'Nike long sleeve '),
        ('Nike_longsleeve_12', 'Nike long sleeve '),
        ('Nike_longsleeve_13', 'Nike long sleeve '),
        ('Nike_longsleeve_14', 'Nike long sleeve '),
        ('Nike_longsleeve_15', 'Nike long sleeve '),
        ('Nike_longsleeve_16', 'Nike long sleeve '),
        ('Nike_longsleeve_17', 'Nike long sleeve '),
        ('Nike_longsleeve_18', 'Nike long sleeve '),
        ('Nike_longsleeve_19', 'Nike long sleeve ');
